[package]
name = "neon"
version = "0.1.0"
authors = ["Peter Czibik <p.czibik@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.21"

[dependencies]
neon = "0.1.21"
url = "1.6"
